# Generated by Django 4.2.9 on 2026-04-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='teachers/')),
                ('description', models.TextField()),
                ('age_range', models.CharField(choices=[('20-30', '20-30'), ('30-40', '30-40'), ('40-50', '40-50'), ('50-60', '50-60'), ('60+', '60+')], max_length=10)),
                ('is_verified', models.BooleanField(default=True)),
                ('gender_bias_score', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
            ],
        ),
    ]
