# Generated by Django 4.2.9 on 2026-04-13 05:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('file', models.FileField(blank=True, upload_to='materials/')),
                ('type', models.CharField(choices=[('lecture', 'Lecture Notes'), ('exam', 'Past Exams'), ('book', 'Book/Reference'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
