# Generated by Django 4.2.9 on 2026-04-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('mandatory', 'Mandatory'), ('elective', 'Elective'), ('major', 'Major'), ('minor', 'Minor'), ('profile', 'Profile')], max_length=20)),
                ('credits', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
