# Generated by Django 4.2.9 on 2026-04-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_interval', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('Lecturer', 'Lecturer'), ('Practice', 'Practice'), ('Labs', 'Labs'), ('All', 'All')], default='Lecturer', max_length=50)),
                ('grading_policy', models.TextField()),
                ('weekly_plan', models.JSONField(default=list)),
                ('grade_distribution', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SyllabusVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='syllabi/')),
                ('year', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
