# Generated by Django 4.2.9 on 2026-04-13 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabusversion',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_instances', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='syllabus_history',
            field=models.ManyToManyField(blank=True, to='courses.syllabusversion'),
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_instances', to='teachers.teacher'),
        ),
    ]
