# Generated by Django 6.0.3 on 2026-04-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_courseinstance_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinstance',
            name='role',
            field=models.CharField(choices=[('Lecturer', 'Lecturer'), ('Practice', 'Practice'), ('Labs', 'Labs'), ('All', 'All')], default='Lecturer', max_length=50),
        ),
    ]
